### ISSUE TITLE
"Edit on Github" leads to a 404

### ISSUE THREAD

**Issue by CleoQc** [DexterInd/micropython-gigglebot#8]
No idea why yet. It seems it's not set up properly somewhere

**Comment by CleoQc** [comment]
bug was with readthedocs, now fixed

**Comment by RobertLucian** [comment]
Was this bug fixed in https://github.com/DexterInd/micropython-gigglebot/pull/7?

**Comment by CleoQc** [comment]
It was fixed by re-building the documentation on Github. It was their hiccup.

**Comment by RobertLucian** [comment]
Oh yeah, that seems to happen from time to time.
